const ALGOLIA_APP_ID = process.env.GATSBY_ALGOLIA_APP_ID
const ALGOLIA_API_KEY = process.env.GATSBY_ALGOLIA_ADMIN_KEY
const ALGOLIA_SEARCH_KEY = process.env.GATSBY_ALGOLIA_SEARCH_KEY
const ALGOLIA_INDEX_NAME = process.env.GATSBY_ALGOLIA_INDEX_NAME

export {
	ALGOLIA_APP_ID,
	ALGOLIA_API_KEY,
	ALGOLIA_SEARCH_KEY,
	ALGOLIA_INDEX_NAME
}
