[build.environment]
NODE_VERSION = "20.14.0" # - latest NODE version
NPM_VERSION = "10.8.1"   # - latest NPM version
YARN_VERSION = "1.22.22" # - latest YARN version

[dev]
command = "yarn develop"
publish = "public"
